[package]
name = "todo-list"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
iced = { version = "0.13.1", features = ["tokio"] }
json = "0.12.4"
tokio = { version = "1.45.0", features = ["fs"] }
